parameters:
    buildCOnfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build the project - ${{ parameters.buildConfiguration}}'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration}}'
    projects: '**/RESTAPI_v2/RESTAPI_v2.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.buildConfiguration}}'
  inputs:
    command: 'publish'
    project: '**/RESTAPI_v2/RESTAPI_v2.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration}} --output $(Buid.ArtifactStagingDirectory)/${{ parameters.buildConfiguration}}'
    zipAfterPublish: true